name: "Run Locust tests"
description: "Run Locust load tests in GitHub Actions with thresholds and artifact uploads"
author: "locustio community"
branding:
  icon: "zap"
  color: "orange"

inputs:
  locust-file:
    description: "Path to locust file (e.g., tests/locustfile.py)"
    required: true
  host:
    description: "Target host, e.g. https://example.com"
    required: true
  users:
    description: "Number of simulated users (equivalent to -u/--users)"
    required: false
    default: ""
  spawn-rate:
    description: "Rate to spawn users per second (equivalent to -r/--spawn-rate)"
    required: false
    default: ""
  run-time:
    description: "Total run time (e.g., 2m, 30s)"
    required: false
    default: ""
  headless:
    description: "Run in headless mode"
    required: false
    default: "true"
  tags:
    description: "Only run tasks with any of these tags (comma-separated)"
    required: false
    default: ""
  exclude-tags:
    description: "Exclude tasks with any of these tags (comma-separated)"
    required: false
    default: ""
  log-level:
    description: "Set locust log level (e.g., INFO, DEBUG)"
    required: false
    default: "INFO"
  additional-args:
    description: "Additional raw args to append to the locust command"
    required: false
    default: ""

  # Threshold checks
  check-fail-ratio:
    description: "Fail if (failures/requests) > this ratio (e.g., 0.02)"
    required: false
    default: ""
  check-avg-response-time:
    description: "Fail if aggregated average response time (ms) > value"
    required: false
    default: ""
  check-p95-response-time:
    description: "Fail if aggregated 95th percentile response time (ms) > value"
    required: false
    default: ""

  # Environment setup
  python-version:
    description: "Python version to use"
    required: false
    default: "3.11"
  locust-version:
    description: "Locust version specifier (e.g., 2.29.1 or ~=2.29)"
    required: false
    default: ""
  requirements:
    description: "Path to requirements file to pip install before running"
    required: false
    default: ""

  # Reports & artifacts
  output-dir:
    description: "Directory to place reports (HTML and CSVs)"
    required: false
    default: "locust-report"
  csv-prefix:
    description: "CSV filename prefix (without path)"
    required: false
    default: "locust_stats"
  html-report:
    description: "Generate HTML report"
    required: false
    default: "true"
  upload-artifacts:
    description: "Upload reports as workflow artifacts"
    required: false
    default: "true"
  artifact-name:
    description: "Artifact name when uploading"
    required: false
    default: "locust-report"

outputs:
  fail_ratio:
    description: "Aggregated failure ratio"
    value: ${{ steps.parse.outputs.fail_ratio }}
  avg_response_time:
    description: "Aggregated average response time (ms)"
    value: ${{ steps.parse.outputs.avg_response_time }}
  p95_response_time:
    description: "Aggregated 95th percentile response time (ms)"
    value: ${{ steps.parse.outputs.p95_response_time }}
  total_requests:
    description: "Total number of requests"
    value: ${{ steps.parse.outputs.total_requests }}
  total_failures:
    description: "Total number of failures"
    value: ${{ steps.parse.outputs.total_failures }}
  thresholds_passed:
    description: "Whether threshold checks passed"
    value: ${{ steps.parse.outputs.thresholds_passed }}

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Upgrade pip
      shell: bash
      run: |
        python -m pip install --upgrade pip

    - name: Install requirements (optional)
      if: ${{ inputs.requirements != '' }}
      shell: bash
      run: |
        python -m pip install -r "${{ inputs.requirements }}"

    - name: Install Locust
      shell: bash
      run: |
        SPEC="${{ inputs.locust-version }}"
        if [[ -n "$SPEC" ]]; then
          if [[ "$SPEC" =~ ^[<>=!~] ]]; then
            python -m pip install "locust$SPEC"
          else
            python -m pip install "locust==$SPEC"
          fi
        else
          python -m pip install locust
        fi

    - name: Prepare output directory
      id: prep
      shell: bash
      run: |
        OUT_DIR="${{ inputs.output-dir }}"
        mkdir -p "$OUT_DIR"
        echo "out_dir=$OUT_DIR" >> "$GITHUB_OUTPUT"
        echo "csv_prefix=${{ inputs.csv-prefix }}" >> "$GITHUB_OUTPUT"

    - name: Run Locust
      id: run_locust
      shell: bash
      run: |
        set -euo pipefail
        OUT_DIR="${{ steps.prep.outputs.out_dir }}"
        CSV_PREFIX="${{ steps.prep.outputs.csv_prefix }}"
        LOCUST_ARGS=(
          -f "${{ inputs.locust-file }}"
          --host "${{ inputs.host }}"
        )
        if [[ "${{ inputs.headless }}" == "true" ]]; then
          LOCUST_ARGS+=(--headless)
        fi
        if [[ -n "${{ inputs.users }}" ]]; then
          LOCUST_ARGS+=(-u "${{ inputs.users }}")
        fi
        if [[ -n "${{ inputs.spawn-rate }}" ]]; then
          LOCUST_ARGS+=(-r "${{ inputs.spawn-rate }}")
        fi
        if [[ -n "${{ inputs.run-time }}" ]]; then
          LOCUST_ARGS+=(-t "${{ inputs.run-time }}")
        fi
        if [[ -n "${{ inputs.tags }}" ]]; then
          LOCUST_ARGS+=(--tags "${{ inputs.tags }}")
        fi
        if [[ -n "${{ inputs.exclude-tags }}" ]]; then
          LOCUST_ARGS+=(--exclude-tags "${{ inputs.exclude-tags }}")
        fi
        if [[ -n "${{ inputs.log-level }}" ]]; then
          LOCUST_ARGS+=(--loglevel "${{ inputs.log-level }}")
        fi
        if [[ "${{ inputs.html-report }}" == "true" ]]; then
          LOCUST_ARGS+=(--html "$OUT_DIR/report.html")
        fi
        LOCUST_ARGS+=(--csv "$OUT_DIR/$CSV_PREFIX")
        if [[ -n "${{ inputs.additional-args }}" ]]; then
          read -r -a EXTRA <<< "${{ inputs.additional-args }}"
          LOCUST_ARGS+=("${EXTRA[@]}")
        fi
        echo "Running: locust ${LOCUST_ARGS[*]}"
        locust "${LOCUST_ARGS[@]}"

    - name: Parse results and enforce thresholds
      id: parse
      shell: bash
      run: |
        set -euo pipefail
        OUT_DIR="${{ steps.prep.outputs.out_dir }}"
        CSV_PREFIX="${{ steps.prep.outputs.csv_prefix }}"
        CSV_PATH="$OUT_DIR/${CSV_PREFIX}_stats.csv"
        python "$GITHUB_ACTION_PATH/src/parse_stats.py" \
          --csv-path "$CSV_PATH" \
          ${INPUT_CHECK_FAIL_RATIO:+--check-fail-ratio "$INPUT_CHECK_FAIL_RATIO"} \
          ${INPUT_CHECK_AVG_RESPONSE_TIME:+--check-avg-response-time "$INPUT_CHECK_AVG_RESPONSE_TIME"} \
          ${INPUT_CHECK_P95_RESPONSE_TIME:+--check-p95-response-time "$INPUT_CHECK_P95_RESPONSE_TIME"} \
          --github-output "$GITHUB_OUTPUT"
      env:
        INPUT_CHECK_FAIL_RATIO: ${{ inputs["check-fail-ratio"] }}
        INPUT_CHECK_AVG_RESPONSE_TIME: ${{ inputs["check-avg-response-time"] }}
        INPUT_CHECK_P95_RESPONSE_TIME: ${{ inputs["check-p95-response-time"] }}

    - name: Upload artifacts (optional)
      if: ${{ inputs.upload-artifacts == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: |
          ${{ steps.prep.outputs.out_dir }}/*.html
          ${{ steps.prep.outputs.out_dir }}/*.csv


