name: "Run Locust tests"
description: "Run Locust load tests in GitHub Actions with thresholds and artifact uploads"
author: "locustio community"
branding:
  icon: "zap"
  color: "orange"

inputs:
  locust_file:
    description: "Path to locust file (e.g., tests/locustfile.py)"
    required: false
  args:
    description: "Raw CLI args to append to the locust command (preferred over specific inputs)"
    required: false
    default: ""
  config_file:
    description: "Path to Locust config file passed with --config"
    required: false
    default: ""
  csv_base:
    description: "Base path (dir/file) for Locust CSV/HTML reports, e.g. locust-report/locust_stats"
    required: false
    default: "locust-report/locust_stats"
  html_report:
    description: "Generate HTML report"
    required: false
    default: "true"
  upload_artifacts:
    description: "Upload reports as workflow artifacts"
    required: false
    default: "true"
  artifact_name:
    description: "Artifact name when uploading"
    required: false
    default: "locust-report"

outputs:
  fail_ratio:
    description: "Aggregated failure ratio"
    value: ${{ steps.parse.outputs.fail_ratio }}
  avg_response_time:
    description: "Aggregated average response time (ms)"
    value: ${{ steps.parse.outputs.avg_response_time }}
  p95_response_time:
    description: "Aggregated 95th percentile response time (ms)"
    value: ${{ steps.parse.outputs.p95_response_time }}
  total_requests:
    description: "Total number of requests"
    value: ${{ steps.parse.outputs.total_requests }}
  total_failures:
    description: "Total number of failures"
    value: ${{ steps.parse.outputs.total_failures }}

runs:
  using: "composite"
  steps:
    - name: Prepare output directory
      id: prep
      shell: bash
      run: |
        set -euo pipefail
        CSV_BASE="${{ inputs.csv_base }}"
        CSV_DIR="$(dirname "$CSV_BASE")"
        mkdir -p "$CSV_DIR"
        echo "out_dir=$CSV_DIR" >> "$GITHUB_OUTPUT"
        echo "csv_base=$CSV_BASE" >> "$GITHUB_OUTPUT"

    - name: Validate required inputs
      shell: bash
      run: |
        set -euo pipefail
        if [[ -n "${{ inputs.locust_file }}" ]]; then
          if [[ ! -f "${{ inputs.locust_file }}" ]]; then
            echo "locust_file not found: ${{ inputs.locust_file }}" >&2
            exit 1
          fi
        fi

    - name: Run Locust
      id: run_locust
      shell: bash
      run: |
        set -uo pipefail
        OUT_DIR="${{ steps.prep.outputs.out_dir }}"
        CSV_BASE="${{ steps.prep.outputs.csv_base }}"
        LOCUST_ARGS=(
        )
        if [[ -n "${{ inputs.locust_file }}" ]]; then
          LOCUST_ARGS+=(-f "${{ inputs.locust_file }}")
        fi
        LOCUST_ARGS+=(--headless)
        if [[ -n "${{ inputs.config_file }}" ]]; then
          LOCUST_ARGS+=(--config "${{ inputs.config_file }}")
        fi
        if [[ "${{ inputs.html_report }}" == "true" ]]; then
          LOCUST_ARGS+=(--html "${CSV_BASE}.html")
        fi
        LOCUST_ARGS+=(--csv "$CSV_BASE")
        if [[ -n "${{ inputs.args }}" ]]; then
          read -r -a EXTRA2 <<< "${{ inputs.args }}"
          LOCUST_ARGS+=("${EXTRA2[@]}")
        fi
        echo "Running: locust ${LOCUST_ARGS[*]}"
        set +e
        locust "${LOCUST_ARGS[@]}"
        STATUS=$?
        set -e
        echo "exit_code=$STATUS" >> "$GITHUB_OUTPUT"

    - name: Parse results and enforce thresholds
      id: parse
      shell: bash
      run: |
        set -uo pipefail
        CSV_BASE="${{ steps.prep.outputs.csv_base }}"
        CSV_PATH="${CSV_BASE}_stats.csv"
        LOCUST_EXIT="${{ steps.run_locust.outputs.exit_code }}"
        # Always parse to produce outputs; do not enforce thresholds. Propagate Locust's exit code.
        python "$GITHUB_ACTION_PATH/src/parse_stats.py" \
          --csv-path "$CSV_PATH" \
          --github-output "$GITHUB_OUTPUT" || true
        exit "$LOCUST_EXIT"

    - name: Upload artifacts (optional)
      if: ${{ inputs.upload_artifacts == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: |
          ${{ steps.prep.outputs.out_dir }}/*.html
          ${{ steps.prep.outputs.out_dir }}/*.csv
